import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Template from "./components/template";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
const fullWidth = {
  maxWidth: "1440px",
  margin: "0 auto",
}

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"  className="h-full bg-gray-100">
      <body 
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Template children={undefined} titulo={""} />
        {children}
      </body>
    </html>
  );
}
